include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_const_constructors: false
    use_build_context_synchronously: false
    deprecated_member_use: false
analyzer:
  errors:
    deprecated_member_use: ignore
