# Generated by Django 6.1.1 on 2026-09-24 18:41

import datetime
import django.db.models.deletion
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('mode', models.CharField(default='inventory', max_length=16)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('perishability', models.CharField(choices=[('high', 'High (hours to days)'), ('medium', 'Medium (days to weeks)'), ('low', 'Low (weeks to months)')], max_length=8)),
                ('storage', models.CharField(choices=[('frozen', 'Frozen (-18 °C)'), ('chilled', 'Chilled (0-5 °C)'), ('ambient', 'Ambient / dry'), ('hot_hold', 'Hot holding (>63 °C)')], max_length=10)),
                ('storage_temp_c', models.CharField(blank=True, max_length=20)),
                ('default_shelf_life_days', models.PositiveIntegerField()),
                ('warning_days', models.PositiveIntegerField(help_text='Alert when days-to-expiry <= this')),
                ('critical_days', models.PositiveIntegerField(help_text='Critical alert when days-to-expiry <= this')),
                ('co2e_per_kg', models.FloatField(default=2.5, help_text='kg CO2e avoided per kg rescued')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated words used by the auto-classifier')),
                ('handling_notes', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(default='#1FA463', max_length=9)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.foodcategory')),
            ],
            options={
                'verbose_name_plural': 'food categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='POSIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('provider', models.CharField(choices=[('generic', 'Generic REST'), ('square', 'Square'), ('lightspeed', 'Lightspeed'), ('petpooja', 'Petpooja'), ('toast', 'Toast')], default='generic', max_length=16)),
                ('api_key', models.CharField(default=inventory.models._new_key, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('events_received', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_integrations', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(max_length=64)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre'), ('pcs', 'Pieces'), ('pack', 'Pack'), ('portion', 'Portion / meal')], default='kg', max_length=8)),
                ('unit_weight_kg', models.FloatField(default=1.0, help_text='kg per unit, used for impact metrics')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, help_text='Overrides category default', null=True)),
                ('reorder_point', models.FloatField(default=0)),
                ('storage_space_per_unit_kg', models.FloatField(default=1.0)),
                ('fr_product_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('fr_first_category_id', models.IntegerField(blank=True, null=True)),
                ('fr_second_category_id', models.IntegerField(blank=True, null=True)),
                ('fr_third_category_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.foodcategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(blank=True, max_length=64)),
                ('quantity', models.FloatField()),
                ('initial_quantity', models.FloatField(default=0)),
                ('received_date', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField()),
                ('storage_location', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiring', 'Expiring soon'), ('expired', 'Expired'), ('listed', 'Listed for donation'), ('depleted', 'Depleted')], db_index=True, default='active', max_length=10)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('unknown', 'Not scored'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='unknown', max_length=10)),
                ('risk_factors', models.JSONField(blank=True, default=dict)),
                ('predicted_demand', models.FloatField(blank=True, help_text='Units forecast to sell before expiry', null=True)),
                ('expected_waste_qty', models.FloatField(blank=True, null=True)),
                ('recommended_action', models.CharField(blank=True, max_length=200)),
                ('risk_model', models.CharField(blank=True, max_length=40)),
                ('risk_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accounts.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'ordering': ['expiry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('purchase', 'Purchase / receipt'), ('sale', 'Sale'), ('waste', 'Waste / discard'), ('donation', 'Donation'), ('adjustment', 'Stock adjustment'), ('return', 'Return')], db_index=True, max_length=12)),
                ('quantity', models.FloatField(help_text='Always positive; direction comes from txn_type')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('csv', 'CSV upload'), ('pos', 'POS integration'), ('scan', 'Barcode scan'), ('import', 'Dataset import'), ('system', 'System')], default='manual', max_length=8)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('holiday_flag', models.BooleanField(default=False)),
                ('activity_flag', models.BooleanField(default=False)),
                ('stockout_hours', models.PositiveSmallIntegerField(default=0)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.inventorybatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.product')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpiryThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_days', models.PositiveIntegerField()),
                ('critical_days', models.PositiveIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_thresholds', to='accounts.organization')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.foodcategory')),
            ],
            options={
                'unique_together': {('organization', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ExpiryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('warning', 'Approaching expiry'), ('critical', 'Critical'), ('expired', 'Expired')], max_length=10)),
                ('days_left', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='accounts.organization')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.inventorybatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('batch', 'level')},
            },
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['organization', 'status', 'expiry_date'], name='inventory_i_organiz_066b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['organization', 'product', 'txn_type', 'occurred_at'], name='inventory_s_organiz_d6dd36_idx'),
        ),
    ]
