# Generated by Django 6.1.1 on 2026-09-24 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGORequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('min_quantity_kg', models.FloatField(default=0)),
                ('max_quantity_kg', models.FloatField(default=500)),
                ('max_distance_km', models.FloatField(default=15)),
                ('dietary_restrictions', models.JSONField(blank=True, default=list, help_text="Tags the NGO can accept only, e.g. ['veg']")),
                ('has_refrigeration', models.BooleanField(default=False)),
                ('pickup_days', models.JSONField(blank=True, default=list, help_text='0=Mon … 6=Sun; empty = any day')),
                ('pickup_from_hour', models.PositiveSmallIntegerField(default=8)),
                ('pickup_to_hour', models.PositiveSmallIntegerField(default=21)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='inventory.foodcategory')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('breakdown', models.JSONField(default=dict)),
                ('reasons', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('requested', 'Pickup requested'), ('declined', 'Declined')], default='suggested', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='accounts.organization')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.ngorequirement')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='SurplusListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('quantity_kg', models.FloatField()),
                ('quantity_units', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(default='kg', max_length=12)),
                ('expiry_date', models.DateField()),
                ('pickup_address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('handling_notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Fully reserved'), ('completed', 'Picked up'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=10)),
                ('auto_suggested', models.BooleanField(default=False, help_text='Created from an AI waste-risk suggestion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='inventory.inventorybatch')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.foodcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.FloatField()),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'Awaiting confirmation'), ('confirmed', 'Scheduled'), ('in_transit', 'In transit'), ('completed', 'Delivered'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], db_index=True, default='requested', max_length=12)),
                ('initiated_by', models.CharField(default='ngo', help_text='ngo = claim, donor = offer', max_length=8)),
                ('donor_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('ngo_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_received_kg', models.FloatField(blank=True, null=True)),
                ('meals_served', models.PositiveIntegerField(blank=True, null=True)),
                ('beneficiaries_served', models.PositiveIntegerField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=80)),
                ('driver_phone', models.CharField(blank=True, max_length=32)),
                ('vehicle', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.match')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='accounts.organization')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='marketplace.surpluslisting')),
            ],
            options={
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='marketplace.surpluslisting'),
        ),
        migrations.CreateModel(
            name='AvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='marketplace.surpluslisting')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('listing', 'ngo')},
        ),
    ]
